version: "3.7"

services:

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ACCESS_KEY=TESTKEY
      - MINIO_SECRET_KEY=TESTSECRET
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 35s
      timeout: 20s
      retries: 3
    command: server --compat /data

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  master:
    container_name: master
    image: paualarco/master:0.1.17
    ports:
      - 8080:8080
      - 9081:9081
