apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
  labels:
    app: master
spec:
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
        - name: dispatcher
          image: "{{ .Values.dispatcher.image.repository }}:{{ .Values.dispatcher.image.tag }}"
          env:
            {{- range $key, $value := .Values.dispatcher.appConfig }}
            - name: {{ $key | snakecase | upper }}
              value: {{ $value | quote }}
            {{- end}}
          imagePullPolicy: {{ .Values.dispatcher.image.pullPolicy }}
          resources:
            {{- toYaml .Values.dispatcher.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: slave
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          env:
          - name: GRPC_SERVER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- range $key, $value := .Values.worker.appConfig }}
          - name: {{ $key | snakecase | upper }}
            value: {{ $value | quote }}
          {{- end}}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}