apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
  labels:
    app: master
spec:
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag }}"
          env:
            {{- range $key, $value := .Values.master.appConfig }}
            - name: {{ $key | snakecase | upper }}
              value: {{ $value | quote }}
            {{- end}}
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave
  labels:
    app: slave
spec:
  replicas: {{ .Values.slave.replicas }}
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
        - name: slave
          image: "{{ .Values.slave.image.repository }}:{{ .Values.slave.image.tag }}"
          env:
          - name: GRPC_SERVER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          {{- range $key, $value := .Values.slave.appConfig }}
          - name: {{ $key | snakecase | upper }}
            value: {{ $value | quote }}
          {{- end}}
          imagePullPolicy: {{ .Values.slave.image.pullPolicy }}
          resources:
            {{- toYaml .Values.slave.resources | nindent 12 }}